import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { 
  MapPin, 
  ArrowRight,
  Compass,
  Brain,
  ShieldAlert,
  BarChart3,
  ShieldCheck,
  Building2,
  GitFork,
  PhoneCall
} from 'lucide-react';

const UserDashboard = () => {
  const { user } = useAuth();

  const studentModules = [
    {
      title: "Interactive Campus Map",
      description: "Explore 12 campus buildings, 25+ pedestrian junctions, corridor paths, and real-time crowd heatmaps.",
      link: "/map",
      icon: MapPin,
      badge: "GIS & Map",
      accent: "text-blue-400 border-blue-500/30 bg-blue-500/10"
    },
    {
      title: "Intelligent Route Finder",
      description: "Calculate Normal Shortest, Fastest, Crowd-Aware, and Alternative bypass routes with live ETAs.",
      link: "/routes",
      icon: Compass,
      badge: "Smart Routing",
      accent: "text-emerald-400 border-emerald-500/30 bg-emerald-500/10"
    },
    {
      title: "AI Crowd Prediction",
      description: "View 24-hour forecasted congestion levels generated by trained Random Forest machine learning models.",
      link: "/predictions",
      icon: Brain,
      badge: "AI Forecasting",
      accent: "text-purple-400 border-purple-500/30 bg-purple-500/10"
    },
    {
      title: "Emergency Evacuation Guidance",
      description: "Live safety directions, closest perimeter exit calculation, and real-time hazard avoidance routes.",
      link: "/emergency",
      icon: ShieldAlert,
      badge: "Safety & Evac",
      accent: "text-red-400 border-red-500/30 bg-red-500/10"
    },
    {
      title: "Campus Crowd Analytics",
      description: "Visual density charts, zone utilization analytics, and peak congestion breakdowns across campus.",
      link: "/analytics",
      icon: BarChart3,
      badge: "Live Analytics",
      accent: "text-cyan-400 border-cyan-500/30 bg-cyan-500/10"
    }
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Welcome Banner */}
      <div className="bg-gradient-to-r from-slate-800 via-slate-800/90 to-slate-900 border border-slate-700/80 rounded-2xl p-6 sm:p-8 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Welcome back, {user?.name || 'Student'}!
            </h1>
            <p className="text-slate-300 text-sm mt-1.5 max-w-2xl leading-relaxed">
              Real-time campus crowd monitoring, congestion-aware route navigation, AI predictions, and emergency evacuation guidance.
            </p>
          </div>
          <div className="flex items-center gap-2 self-start sm:self-auto">
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
              All Services Online
            </span>
          </div>
        </div>
      </div>

      {/* Live Campus Quick Status Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-5 backdrop-blur">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-400">Campus Status</span>
            <ShieldCheck className="w-5 h-5 text-emerald-400" />
          </div>
          <p className="text-2xl font-bold text-emerald-400 mt-2">Normal</p>
          <p className="text-xs text-slate-400 mt-1">All academic zones open</p>
        </div>

        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-5 backdrop-blur">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-400">Monitored Facilities</span>
            <Building2 className="w-5 h-5 text-blue-400" />
          </div>
          <p className="text-2xl font-bold text-white mt-2">12 Locations</p>
          <p className="text-xs text-slate-400 mt-1">Real-time crowd tracking</p>
        </div>

        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-5 backdrop-blur">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-400">Corridor Paths</span>
            <GitFork className="w-5 h-5 text-purple-400" />
          </div>
          <p className="text-2xl font-bold text-white mt-2">30 Routes</p>
          <p className="text-xs text-slate-400 mt-1">Available for navigation</p>
        </div>

        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-5 backdrop-blur">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-slate-400">Emergency Alerts</span>
            <ShieldAlert className="w-5 h-5 text-emerald-400" />
          </div>
          <p className="text-2xl font-bold text-emerald-400 mt-2">0 Active</p>
          <p className="text-xs text-slate-400 mt-1">Safe campus environment</p>
        </div>
      </div>

      {/* Campus Safety & Navigation Modules */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-white">
            Campus Navigation & Safety Services
          </h2>
          <span className="text-xs text-slate-400">Select any service to get started</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {studentModules.map((mod, idx) => {
            const Icon = mod.icon;
            return (
              <Link
                key={idx}
                to={mod.link}
                className="bg-slate-800/60 border border-slate-700 hover:border-blue-500/50 rounded-2xl p-5 backdrop-blur transition-all duration-200 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/5 group flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <div className="p-2.5 rounded-xl bg-slate-900/80 border border-slate-700/80 group-hover:border-blue-500/40 transition-colors">
                      <Icon className="w-5 h-5 text-blue-400 group-hover:text-blue-300" />
                    </div>
                    <span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full border ${mod.accent}`}>
                      {mod.badge}
                    </span>
                  </div>
                  <h3 className="font-bold text-white text-base group-hover:text-blue-300 transition-colors">
                    {mod.title}
                  </h3>
                  <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                    {mod.description}
                  </p>
                </div>

                <div className="mt-4 pt-3 border-t border-slate-700/60 flex items-center justify-between text-xs font-bold text-blue-400 group-hover:text-blue-300">
                  <span>Open Service</span>
                  <ArrowRight className="w-4 h-4 transform group-hover:translate-x-1 transition-transform" />
                </div>
              </Link>
            );
          })}
        </div>
      </div>

      {/* Emergency Assistance Hotline Card */}
      <div className="bg-slate-800/40 border border-slate-700/80 rounded-2xl p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3.5">
          <div className="p-2.5 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400">
            <PhoneCall className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">Campus Security & Emergency Assistance</h4>
            <p className="text-xs text-slate-400 mt-0.5">In case of an on-campus incident or medical emergency, contact safety dispatch immediately.</p>
          </div>
        </div>
        <Link
          to="/emergency"
          className="px-4 py-2 bg-red-600 hover:bg-red-500 text-white rounded-xl text-xs font-bold transition-colors whitespace-nowrap"
        >
          View Emergency Directions
        </Link>
      </div>
    </div>
  );
};

export default UserDashboard;
